// @tokenlighten/types — shared contracts for the TokenLighten monorepo.
// Every other package type-checks against these re-exports.

export type {
  McpToolResult,
  LocateInput,
  LocateHitData,
  LocateAbstainData,
  LocateCandidateDetail,
  LocateOutput,
  ImpactSurface,
  ImpactCandidate,
  ConcernCoverage,
  ConcernEvidenceClass,
  ConcernEvidenceConflict,
  ConcernEvidenceConflictPosition,
  ConcernEvidenceSubclass,
  ConcernEvidenceSurface,
  TaskChangeObligationKind,
  TaskChangeObligation,
  TaskChangeContract,
  TaskWiringEvidence,
  TaskEvidenceRelationKind,
  TaskEvidenceRole,
  TaskEvidenceNode,
  TaskEvidenceRelation,
  TaskEvidenceGraph,
  TaskWiringEndpoint,
  TaskVerificationRecipe,
  TaskWiringStructuralCheck,
  TaskWiringCompletionProof,
  TaskWiringConnection,
  TaskWiringProfile,
  TaskProfile,
  TaskProfileRequest,
  TaskProfileBinding,
  TaskReadinessEvidence,
  TaskReadinessObligation,
  TaskFalsificationReport,
  TaskReadinessRisk,
  TaskReadinessCertificate,
  TaskWorkspaceState,
  TaskDecisionEvidenceClaim,
  TaskDecisionEvidenceModel,
  TaskCapabilityGap,
  TaskSemanticClosure,
  TaskExecutionTypestate,
  TaskCallBudget,
  TaskExecutionContract,
  TaskPackSingleSiteUniqueMatchFastPath,
  ReadCodeTaskPackSurface,
  ReadCodeTaskPackOutput,
  McpLang,
  ReadCodePackRequestItem,
  ReadCodePackInput,
  ReadCodePackResponseItem,
  ReadCodePackOutput,
  EditReviewInfo,
  HandleRef,
  EditFailure,
  ReadCodeMapOutput,
  ReadCodeDigestOutput,
  ReadCodeSliceOutput,
  ReadCodeFullOutput,
  ReadCodeFullBatchResponseItem,
  ReadCodeFullBatchOutput,
  ReadCodeOverviewOutput,
  ReadCodeHandlesBatchResponseItem,
  ReadCodeHandlesBatchOutput,
  BatchEditPathItem,
  BatchEditHandleSearchItem,
  BatchEditHandleContentItem,
  BatchEditItem,
  ArchiveFormat,
  ArchiveSelector,
  ArchiveFailureCode,
  ReadFileArchiveInput,
  ReadFileArchiveEntry,
  ReadFileArchiveOutput,
  ArchiveMemberProvenance,
} from "./mcp.js";

export {
  MCP_LANGS,
  MCP_LANG_EXTS,
} from "./mcp.js";

// ---------------------------------------------------------------------------
// protocol v1 — the frozen MCP wire contract.
//
// NORMATIVE SOURCE: DESIGN-v0.10-protocol-v1-contract-freeze.md §10.3
// (Appendix A, Revision 4, user-approved 2026-08-13); file placement per A.9.1.
//
// A downstream SDK's exhaustive switch (§6.1(g)) imports `ProtocolResult` and
// NOTHING ELSE. The four family unions — `ReadResult`, `SearchResult`,
// `EditResult`, and `Refusal` (the single-member refusal family) — are exported
// beside it so a consumer can narrow one family without re-deriving it.
// ---------------------------------------------------------------------------
export type {
  // A.1 envelope + carrier
  ProtocolVersion,
  Envelope,
  WireResponse,
  // A.5 discrimination contract
  Kind,
  ProtocolResult,
  ReadResult,
  SearchResult,
  EditResult,
  // A.2.1 tool calls
  JsonValue,
  ToolName,
  ToolArguments,
  ToolCallOf,
  ToolCall,
  EditToolCall,
  // A.2.2 / A.2.7 cross-tool leaf types
  WorkspaceMarker,
  CapabilityGap,
  Limit,
  OmittedClass,
  SurfaceRole,
  Evidence,
  FreshEvidence,
  PriorEvidence,
  // A.5.15 + A.7.1 refusal
  Refusal,
  RetryTransition,
  RefusalCode,
  RequestShapeCode,
  HandleCode,
  TypestateCode,
  WriteCode,
  IntentCode,
  ReadLimitCode,
  DocumentCode,
  ArchiveCode,
  ArtifactCode,
  CredentialCode,
  // A.2.3–A.2.6, A.3, A.7.2 decision
  TaskRef,
  CoverageReason,
  CertificateRef,
  Candidate,
  FrontierEntry,
  CreateTarget,
  TaskDecision,
  AwaitInputCode,
  // A.4 receipts
  Receipt,
  // A.5.1–A.5.7 read family
  ReadTaskPackResult,
  ReadTextResult,
  SkeletonProfile,
  ReadMapResult,
  StructuralOutline,
  ReadBatchResult,
  BatchEntry,
  ReadArtifactResult,
  ArtifactContent,
  OoxmlVisualLocation,
  OoxmlChartSeries,
  OoxmlChartInfo,
  OoxmlMediaUse,
  OoxmlMediaInfo,
  OoxmlVisualInventory,
  ReadReceiptResult,
  ReadClosureResult,
  // A.5.8–A.5.10 search family
  SearchMatchesResult,
  SearchMatches,
  SearchReferencesResult,
  SearchTreeResult,
  FindFileGroup,
  FindAbsence,
  FindInventoryFileEntry,
  FindInventoryDirEntry,
  RelatedLookupCall,
  RelatedLookups,
  MemberSweepAttachment,
  Hop1Context,
  SymbolKind,
  SymbolLocation,
  Reference,
  ReferenceFileGroup,
  ReferenceAbsence,
  DiffHunk,
  DiffFile,
  // A.5.11–A.5.14 edit family
  SideEffectCore,
  EditCounts,
  RollbackFileState,
  AppliedEntry,
  NormalizationReceipt,
  EditReclassification,
  EditApplied,
  EditReclassified,
  EditRolledBack,
  EditStateUnknown,
  // A.9.3 request-validation contract
  SchemaNode,
  UnknownPropertyViolation,
  RequestShapeRefusal,
  // A.6.1 plan container + the verification kit
  ProfilePlan,
  VerificationKit,
  BodyMarker,
  VerificationSurface,
  CompileFact,
  LinkSetEntry,
  MockHeaderEntry,
  HarnessInfo,
  ToolchainInfo,
} from "./mcp.js";

export type {
  RankedFile,
  ApiEndpoint,
  ModuleNode,
  RepoSkeleton,
} from "./skeleton.js";

export type {
  SentinelBlock,
  StubTargetId,
  StubTarget,
  GenerateResult,
} from "./agents.js";

export type { TLConfig } from "./config.js";

export type {
  TokenLightenClient,
  TokenLightenTool,
  TokenLightenUsageEvent,
  TokenLightenAutomaticPrice,
  TokenLightenSessionModelUsage,
  TokenLightenReductionInterval,
  TokenLightenSummaryScope,
  TokenLightenSessionEstimate,
  TokenLightenUsageSummary,
  TokenLightenPrivacyReport,
  TokenLightenUsageExportManifest,
} from "./usage.js";

export type {
  TokenLightenSetupClient,
  TokenLightenWorkspaceSetupResult,
  TokenLightenWorkspaceSummary,
  TokenLightenWorkspaceListResult,
} from "./setup.js";

export type {
  TokenLightenRegistrationClient,
  TokenLightenClientRegistrationState,
  TokenLightenLauncherState,
  TokenLightenClientRegistrationStatus,
  TokenLightenClientsResult,
  TokenLightenHostProfile,
  TokenLightenHostProfileReason,
  TokenLightenHostProfileSelection,
  TokenLightenHostActivationInput,
  TokenLightenClientProfileResult,
} from "./clients.js";

// ---------------------------------------------------------------------------
// v0.10 internal domain model — reducer/telemetry types, NOT the wire
// protocol. See `./domain/index.ts`'s header and
// DESIGN-v0.10-expansion-plan-reconciliation.md §3/§5 (D-1/D-2/D-4): the
// wire contract stays exactly what `./mcp/` freezes above; nothing below
// this comment is emitted on the wire in its own shape.
// ---------------------------------------------------------------------------
export type {
  EvidenceId,
  EvidenceRole,
  EvidenceIdentity,
  EvidenceUse,
  DeliveryDisposition,
  EmissionHistory,
  EvidenceDelivery,
  CoverageState,
  ContinuationControl,
  StateHandlePurpose,
  DecodedStateHandle,
  CommonStateInput,
  TrustedClientContextMeta,
  ClientContextAttestation,
  ContextReceipt,
  LocalTaskState,
  ContextAttestationV1,
  ContextAttestationRejection,
  ContextAttestationVerdict,
  ContextGenerationState,
  TaskReasoningIR,
  // V11-04 Task Reasoning IR v2 (additive; v1 above unchanged).
  ValidityKey,
  ObligationOrigin,
  EvidencePredicate,
  ObligationState,
  ObligationNode,
  TombstoneScope,
  DirectAbsenceProof,
  HypothesisTombstone,
  ObligationPatch,
  ReasoningDeltaOp,
  ReasoningDelta,
  TaskReasoningIRv2,
  StopCertificateCandidate,
  TermResult,
  TreeScopeReport,
  HostBudgetProfile,
  EncodingDecision,
  ContributionEstimate,
} from "./domain/index.js";

export {
  EVIDENCE_ROLES,
  isEvidenceRole,
  DELIVERY_DISPOSITIONS,
  isDeliveryDisposition,
  STATE_HANDLE_PURPOSES,
  isStateHandlePurpose,
  HANDLE_WIRE_PREFIXES,
  parseHandlePurposeFromPrefix,
  HANDLE_WIRE_SIZE_TARGET_P95,
  HANDLE_WIRE_SIZE_MAX,
  CONTEXT_STATE_META_KEY,
  CONTEXT_ATTESTATION_VERSION,
} from "./domain/index.js";
